version: '3.8'
services:
  jxl-server:
    image: jxl-converter-webapp
    build:
      context: .
      dockerfile: jxl-converter.Server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "9000:8080"
    restart: unless-stopped
